// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package entities

import (
	"database/sql"
)

type Todo struct {
	ID             string
	Title          sql.NullString
	Description    sql.NullString
	CreatedAt      sql.NullTime
	LastModifiedAt sql.NullTime
	UserID         sql.NullString
}

type User struct {
	ID             string
	Username       sql.NullString
	Email          sql.NullString
	CreatedAt      sql.NullTime
	LastModifiedAt sql.NullTime
}
